export const ADD_PAINTING_CATEGORY = 'ADD_PAINTING_CATEGORY';

export const REMOVE_PAINTING_CATEGORY = 'REMOVE_PAINTING_CATEGORY';

export const ADD_FURNITURE_CATEGORY = 'ADD_FURNITURE_CATEGORY';

export const REMOVE_FURNITURE_CATEGORY = 'REMOVE_FURNITURE_CATEGORY';

export const ADD_CUSTOM_CATEGORY = 'ADD_CUSTOM_CATEGORY';

export const REMOVE_CUSTOM_CATEGORY = 'REMOVE_CUSTOM_CATEGORY';
